### ISSUE TITLE
Features question

### ISSUE THREAD

**Issue by jinxmcg** [yatsenkolesh/dot-js-php-render#2]
Hi,

Do you plan to include the other operations in templates like
{{=it.field || ''}} 
?

Thanks

**Comment by yatsenkolesh** [comment]
Hi. Yes, just write about what do you want to include and star this repository. 👍 
I'll do it on Saturday.

**Comment by jinxmcg** [comment]
I starred it anyway :) is a good port.

I want to make a framework where people can use either php or node as backend and the frontend 
to have the same templates as the backend uses. (basically by using the same templating library doT.js, moustachejs, handlebards etc...)

I liked doT.js performance, found your library and  tested it. Basically I was looking for a library with a full port in PHP. 

Do you have any plans to port it completely?

Thank you

**Comment by yatsenkolesh** [comment]
Yes, if you have a need for this.I like your idea and i will help you to realize it -  will be completely transferred functionality doT.js to php in my library :)

Thank you for.

**Comment by jinxmcg** [comment]
Great! Thanks. Give me your PayPal email to send you some beers! ;)

**Comment by yatsenkolesh** [comment]
Thank you, but I just love code and work on open source projects for yourself. :)
